// wrangler.toml で名前とアカウントを設定
export default {
  async fetch(req) {
    const url = new URL(req.url);
    const q   = url.searchParams.get("q") || "";
    const api = `https://webservice.recruit.co.jp/hotpepper/gourmet/v1/` +
                `?key=${HOTPEPPER_KEY}&keyword=${encodeURIComponent(q)}` +
                `&format=json&count=20`;

    const res = await fetch(api);
    return new Response(res.body, {
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",      // ← ここで CORS を許可
      },
    });
  }
}
